---
- name: Ensure required packages are installed
  apt:
    name:  
      - mysql-server
      - pip
      #installing whois to install mkpasswd module
      - whois
    state: latest
  ignore_errors: true
  notify: Restart SQL

- name: Install Required pip modules
  pip:
    name:
      - PyMySQL
    state: present
    executable: pip3